title: Власов С.
description: Блог. Записи о программировании
author: Сергей Власов
github: https://github.com/g10k - когда будешь писать на github тогда можешь открыть его
github_on: false
about: Заметки для себя, которые могут быть полезны
#disqus_shortname: stackproblems - мне не нужно
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: false
    permalink: /project/:path/
  snippet:
    output: true
    permalink: /snippets/:path/

social:
    - icon: fa-vk
      link: "https://vk.com/g10kvs"
    - icon: fa-twitter
      link: "https://twitter.com/g10kvs"
    - icon: fa-instagram
      link: "https://www.instagram.com/g10kvs/"
    - icon: fa-github
      link: "https://github.com/g10k"

share:
  twitter_username: agusmakmun6
  fb_appid: 1749788565247320

urls:
    - text: Обо мне
      url: /about/
    - text: My Projects
      url: /projects/
      hidden: true

    - text: Snippets
      url: /snippets/

    - text: XML Feed
      url: /feed.xml

url: "https://agusmakmun.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
